import type { Metadata } from "next";
import "../globals.css";
import { Header } from "#/widgets/header/ui/Header";
import { Footer } from "#/widgets/footer/ui/Footer";
import { CreateTask } from "#/features/createTask";
import { TabsOfTasks } from "#/widgets/(tasks)/tabsOfTasks";
import { AuthPanel } from "#/widgets/authPanel";

export const metadata: Metadata = {
  title: "To Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen grid-rows-[auto_auto_auto_1fr_auto]">
      <Header />
      <div className="flex items-center justify-between">
        <CreateTask />
        <AuthPanel />
      </div>
      <TabsOfTasks />
      {children}
      <Footer />
    </div>
  );
}