import { TabsOfGroups } from "#/widgets/(tasks)/tabsOfGroups";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Deadlines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <TabsOfGroups />
      {children}
    </div>
  );
}