import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Авторизация",
    description: "Generated by create next app",
};

export default function ChildLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            {children}
        </div>
    );
}